language: node_js
node_js:
  - "stable"
services:
  - postgresql
before_script:
  - psql -c 'create database cake_boss_test;' -U postgres
script:
  - npm install
  - npm test
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coverage
